### ISSUE TITLE
Misskey support

### ISSUE THREAD

**Issue by hellstabber** [immers-space/guppe#55] opened 2022-06-10 11:34 UTC
I can't follow the group account from my Misskey account. It's on that screen;
![A0745359-0E92-408E-B4AA-55BA03884864](https://user-images.githubusercontent.com/25508537/173056232-fa668c9c-1d75-4274-be69-78c545dc5662.png)

**Comment by guysoft** [comment] 2022-07-03 21:15
@datatitian@social.coop 
Ok, I have a guppe server deployed, and it seem like 
1. following works.
2. there are 500 error messages in the log when I started to follow it from Pleroma:
https://pastebin.com/XhrVr1jh

Its ipv6 only, so if any Misskey users that have IPv6 want to test it then go ahead:
https://guppe.gnethomelinux.com/

Its a test server and will go down eventually (or get redeployed)

**Comment by guysoft** [comment] 2022-07-24 21:22
Ok, I managed to implement follow on fedigroup both for Mastodon and Pleroma.

There was one noticeable difference in how Pleroma handles the accept response - the id.
Mastodon did not look at the id of the message. Pleroma did. 

1. The accept activity id has to be unique each time. otherwise Pleroma log says "I already handled a follow request with this id" and discards it.
2. The request id of the object (the one that Pleroma sends to you when sending the follow request) has to match the request that was sent. 
3. I confirmed that follow works even if I hide the followers list, just to make sure that is not the case.

This would mean having a look at this section and figuring out if the id is sent correctly:
https://github.com/wmurphyrd/guppe/blob/main/index.js#L126

I believe Misskey might have a similar behavior

**Comment by BeeFox-sys** [comment] 2022-11-13 11:00
Any news on if this is closed? it seems that i can't follow, nor even view boosts, from akkoma (which is a fork of pleroma so i imagine the issue is there too).

**Comment by guysoft** [comment] 2022-11-16 08:33
Hey, 
Managed to fix it on my Pleroma end, it works - the issue was that the instance went down for a week and was listed as 
unreachable, I had to update the db entry and it works!

it might be a good idea to check that entry on your missky server, it might be the issue

![Screenshot_20221116_102755](https://user-images.githubusercontent.com/325670/202129191-d5ec4163-243a-4181-b3ef-da293b89c4f0.png)

**Comment by BeeFox-sys** [comment] 2022-11-22 10:58
This was also my issue ^

**Comment by wmurphyrd** [comment] 2022-11-26 19:41
Thanks for the reports. Closing this as fixed

**Closed by wmurphyrd** 2022-11-26 19:41 UTC
